### ISSUE TITLE
Issue restarting docker

### ISSUE THREAD

**Issue by babyfooter** [bitnami/bitnami-docker-owncloud#58]
Hi,

After restarting owncloud docker, I encoured an issue about Apache, error is following 👍 

nami    ERROR Unable to start com.bitnami.apache: Pid file '/opt/bitnami/apache/tmp/httpd.pid' was found but either no proper PID was found or no process is running there.

Owncloud server is setted on port 8084 in docker-compose.yml, and was working file before lat restart.

Do you have an idea?

Thx!

**Comment by juan131** [comment]
Hi @babyfooter 

Did you restart docker (daemon) or did you just restart the container? Anyway.. The PID file it's complaining about is located at `/opt/bitnami/apache/tmp/httpd.pid`, could you try to run the commands below?

```
docker-compose exec owncloud rm /opt/bitnami/apache/tmp/httpd.pid
docker-compose exec owncloud pkill httpd
docker-compose exec owncloud nami start apache
```

**Comment by babyfooter** [comment]
hi @juan131,

Thx for your quick answer, I've stop and up app, all is back now. will test your commands next time.

Thx again.
