### ISSUE TITLE
Failed deployment on Azure when using mounted volumes

### ISSUE THREAD

**Issue by fsocas** [bitnami/bitnami-docker-owncloud#62]
Hi,

I have an issue when deploying on Azure, where, although I can create Bitnami Owncloud docker local containers from this image with no problems at all, but when I deploy to Azure, and volumes, on an Azure Storage Account File Share, to persist data, the "owncloud" container won't start.  
* This Azure Container Group has too Bitnami containers, "mariadb" and "owncloud". 
* Both use Azure Storage Account File Share to persist data.
* Both create mapped files and folder on Azure Storage Account File Share.
* MariaDB containers works great. No problems here.
* Owncloud container, fails to start or load.

This problem is not happening when running this same images (pulled from Azure Container Registry or Docker Hub) locally, using the same settings used in Azure deployment ("mariadb" and "owncloud" environment variables).

**Steps to reproduce the issue:**

1. On an Azure Account, create a Container Registry and pull Bitnami's images from the marketplace.
2. On an Azure Account, create a Storage Account and File Share.
2. Using an **Azure RM Template** (attached)
[ARMTemplate.zip](https://github.com/bitnami/bitnami-docker-owncloud/files/4299484/ARMTemplate.zip)

, deploy Container Group to Azure.
3. Check Container Group on Azure and find "owncloud" container on *Waiting" status.

**Describe the results you received:**
 Error displayed on Azure Container Instance OwnCloud container logs:

```
php     TRACE [runProgram] Executing: /opt/bitnami/php/bin/php occ,status,--no-warnings,--output,json
php     TRACE [runProgram] Executing internal command: /opt/bitnami/php/bin/php ["occ","status","--no-warnings","--output","json"]
php     TRACE [runProgram] RESULT: {"code":1,"stderr":"","stdout":"Console has to be executed with the user that owns the file config/config.php\nCurrent user: daemon\nOwner of config.php: root\nTry adding 'sudo -u root ' to the beginning of the command (without the single quotes)\n"}
Error executing 'postInstallation': Program exited with exit code 1
nami    TRACE Error: Error executing 'postInstallation': Program exited with exit code 1
    at runProgram (/opt/bitnami/nami/node_modules/nami-utils/lib/os/run-program.js:223:14)
    at Object.runProgram (/opt/bitnami/nami/node_modules/nami-utils/lib/os/index.js:63:12)
    at Object.$app.helpers.execute (/root/.nami/components/com.bitnami.php/helpers.js:69:14)
    at Object.<anonymous> (/opt/bitnami/nami/node_modules/lodash/index.js:51:276)
    at Object.$app.helpers.executeOcc (/root/.nami/components/com.bitnami.owncloud/helpers.js:60:22)
    at Object.$app.helpers.upgradeDatabase (/root/.nami/components/com.bitnami.owncloud/helpers.js:108:42)
    at Component.$app.postInstallation (/root/.nami/components/com.bitnami.owncloud/main.js:54:16)
    at Component.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
    at _.each.step (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:32)
    at r (/opt/bitnami/nami/node_modules/lodash/index.js:5:348)
```

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 322
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.943GiB
 Name: docker-desktop
 ID: KMO3:AQYU:ARS6:52HK:UZ7T:WJ3X:MJSX:NP3C:WGSG:WB6D:G6MY:XAG6
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 34
  Goroutines: 51
  System Time: 2020-03-06T16:50:16.6799367Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

Thanks in advance,
Fernando

**Comment by andresbono** [comment]
Hi @fsocas, the issue seems to be that the permissions/ownership are wrong in the volume.

```
Console has to be executed with the user that owns the file config/config.php
Current user: daemon
Owner of config.php: root
```
The container explicitly changes the ownership of the configuration file, so it shouldn't be owned by root at the moment the `occ status` command is executed.

- Can you share with us the full log of the container initialization?
- Can you also make sure the volumes are empty at the time of the initialization? Recreating them should be enough.

**Comment by fsocas** [comment]
Hi @andresbono,
Thanks for your reply.
Yes, seen the error, and even tried replacing permissions myself using the Dockerfile in this repository and a script I made, to "chown" all the "config.php" I could find in the container, but with no luck. 
Weird thing is that in my computaer, MacOS, it works flawlessly.

Attached is the resulting full log after completely emptying the volumes and re deploying the Azure Template: 
[owncloud_ContainerLog.txt](https://github.com/bitnami/bitnami-docker-owncloud/files/4307760/owncloud_ContainerLog.txt)

Regards,
Fernando

**Comment by andresbono** [comment]
Thanks for sharing the logs, @fsocas.

It seems the volumes are mounted as cifs and permissions and ownership are specified in the mount options:

```
$ mount -l | grep /bitnami
//storagecontainers.file.core.windows.net/volumes on /bitnami type cifs (uid=0,noforceuid,gid=0,noforcegid,file_mode=0777,dir_mode=0777)
```

We continue looking for possible solutions.

**Comment by andresbono** [comment]
We couldn't find any option to modify those mount options in Azure Storage File Share. Can you mount a different kind of volume in your environment?

**Comment by fsocas** [comment]
There seems to be no way of mounting different type of volumes on Azure, other than SMB/CIFS. But knowing this, I'll try to replicate the CIFS volume on my machine and see if adding "cifs-utils" to the image helps in any way. I'll let you know if I manage to resolve this, and please tell me if you find any workaround.

Regards,
Fernando

**Comment by andresbono** [comment]
Thanks, @fsocas. It will be helpful for other users if you share your findings.

As a workaround, you might want to create your own custom image from the bitnami one with the following content:

```
FROM bitnami/owncloud:latest

RUN sed -e '/upgradeDatabase/ s|\$|// $|' -i /root/.nami/components/com.bitnami.owncloud/main.js
```

This `sed` is commenting out the function that is causing troubles. This should be enough to avoid the issue you are having, but you won't be able to upgrade your container to a newer version of Owncloud.

**Comment by fsocas** [comment]
Great, I'll give it a try as soon as I can.
Avoiding the function will surely help on troubleshooting and testing.
Unfortunately, I had to jump into another project on a client, so I don't think I'll try it before the end of this week. Should I close the issue for now? Or is there any way I can "stand by" it? (this is my first issue on GitHub)

Thanks again,
Fernando

**Comment by andresbono** [comment]
No problem at all, @fsocas. Thanks for letting us know.

There is no need to close the issue now. If the issue becomes stale, a bot will be pinging us to check again if the issue needs to be closed or not.
