### ISSUE TITLE
Error executing ‘postInstallation’: Program exited with exit code 1

### ISSUE THREAD

**Issue by Mandervain** [bitnami/bitnami-docker-owncloud#64]
Hi, I’ve got a problem with owncloud deployment on Kubernetes Cluster.
I tried to deploy owncloud by helm install.
Unfortunatelly, on owncloud initialization I recived error as below:
Error executing ‘postInstallation’: Program exited with exit code 1

Is there posibility to dig dipper and see what is the couse of this error ?

I tried connect to the database directly from pod in the same namespace and its ok.
I checked core-dns and it looks also ok.
Could anyone give me some advise where could be the problem?

Below are the prints of cluster status for owncloud.

![image](https://user-images.githubusercontent.com/50543691/95191689-604ab480-07d1-11eb-9248-fa5d930f2f60.png)

**Comment by miguelaeh** [comment]
Hi @Mandervain ,
You can try to add the environment variables `BITNAMI_DEBUG=true` and `NAMI_LOG_LEVEL=trace8` to obtain a verbose output

**Comment by Mandervain** [comment]
Thank's for suggestion. Can I add it by values.yaml in helm upgrade -f values.yaml bitnami/owncloud ?

![image](https://user-images.githubusercontent.com/50543691/95446037-0debce00-0960-11eb-8e30-063b78a47361.png)

**Comment by miguelaeh** [comment]
It seems that we were not supporting the `extraEnvVars` for this chart, the PR above add it.
