### ISSUE TITLE
Owncloud config.php not found

### ISSUE THREAD

**Issue by sgomez84** [bitnami/bitnami-docker-owncloud#66]
@migruiz4 I've followed the instruction to start docker with the configuration as per the docker-compose.yml file and MariaDB works fine. But, in the case of Owncloud when I check the logs I get this error of config.php not found.

`realpath: /bitnami/owncloud/config/config.php: No such file or directory`

It would be nice if someone from the contributor team can help me out where things are going wrong.

Here is my docker-compose file:

```
version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_owncloud
      - MARIADB_DATABASE=bitnami_owncloud
    volumes:
      - '/Users/sid/owncloud/data:/bitnami/mariadb'
  owncloud:
    image: 'docker.io/bitnami/owncloud:10-debian-10'
    ports:
      - '8088:8080'
    environment:
      - OWNCLOUD_DATABASE_HOST=mariadb
      - OWNCLOUD_DATABASE_PORT_NUMBER=3306
      - OWNCLOUD_DATABASE_USER=bn_owncloud
      - OWNCLOUD_DATABASE_NAME=bitnami_owncloud
      - ALLOW_EMPTY_PASSWORD=yes
      # Host for accessing ownCloud
      # note: this setting will only be applied on the first run
      # ref: https://github.com/bitnami/bitnami-docker-owncloud#configuration
      - OWNCLOUD_HOST=localhost
    volumes:
      - '/Users/sid/owncloud/data:/bitnami/owncloud'
    depends_on:
      - mariadb
# volumes:
#   mariadb_data:
#     driver: local
#   owncloud_data:
#     driver: local

```

<img width="1015" alt="Screenshot 2021-01-29 at 11 47 29 AM" src="https://user-images.githubusercontent.com/333814/106238971-d616d800-6227-11eb-8a5a-739fbdf61dfd.png">

**Comment by andresbono** [comment]
Hi @sgomez84, what are the contents and permissions of `/Users/sid/owncloud/data` before you start the container?

Are you using Docker for Mac?

**Comment by kirosvi** [comment]
hi. have the same issue. starting use helm chart I've got same error. trying debug I decide to try docker-compose, but same result. docker-compose running on 

`Linux vsdv 5.8.0-41-generic #46~20.04.1-Ubuntu SMP Mon Jan 18 17:52:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

```
# docker-compose version
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

permissions are 777 on folder data

```
 volumes:
      - './data:/bitnami/owncloud'
```

**Comment by andresbono** [comment]
Hi @kirosvi, what are the contents of `./data` before you start the container?

**Comment by kirosvi** [comment]
it was empty. 
after trying install helm chart it contain owncloud folder with necessary structure, so I delete all inside ./data.
once thing I forget to do its recreate folder `./data`. I'll try it later and write again. thanks.

**Comment by kirosvi** [comment]
Hi. sorry for late answer. after recreating folder- all works good. thanks, and sorry for bothering.

**Comment by sgomez84** [comment]
@kirosvi Yes, everything works as expected. Thanks for the clarification.
