### ISSUE TITLE
Function not implemented: AH00141: Could not initialize random number generator

### ISSUE THREAD

**Issue by dominic2708** [bitnami/bitnami-docker-owncloud#67]
Docker version (docker version):18.09.0-0519

i get a issue，thanks

 [:crit] [pid 1] (38)Function not implemented: AH00141: Could not initialize random number generator

**Comment by migruiz4** [comment]
Hi @dominic2708,

Could you please provide more information about your issue?

Any information that would help us reproduce this would be helpful.
